### ISSUE TITLE
Proposal for package reorganization.

### ISSUE THREAD

**Issue by dmitshur** [ConradIrwin/font#10]
I propose we make two changes to make the layout simpler and more idiomatic.

This is the current package organization (as can be seen at https://godoc.org/github.com/ConradIrwin/font):

Path | Synopsis
-----|---------
`github.com/ConradIrwin/font` | Command font.
`github.com/ConradIrwin/font/commands` | Package commands.
`github.com/ConradIrwin/font/sfnt` | Package sfnt provides support for sfnt based font formats.

First, package `commands` is not very useful on its own. See its [godoc](https://godoc.org/github.com/ConradIrwin/font/commands); the functions are not documented and they write directly to `os.Stdout`, returning error. It's only useful for the `font` command. I think we should just merge it into the `font` command itself, its [only known importer](https://godoc.org/github.com/ConradIrwin/font/commands?importers).

Second, I think it'd be nice to move the `font` utility in a `cmd` subdirectory. This is very commonly done for commands, e.g., see https://godoc.org/golang.org/x/tools/cmd, https://godoc.org/cmd, https://godoc.org/upspin.io/cmd, etc. IMO, it's more pleasing to the eye.

The end result would be:

Path | Synopsis
-----|---------
`github.com/ConradIrwin/font/cmd/font` | font is a utility that can parse and print information about font files.
`github.com/ConradIrwin/font/sfnt` | Package sfnt provides support for sfnt based font formats.

What do you think?

**Comment by ConradIrwin** [comment]
Sounds good to me.

Would it be even better to put the sfnt code in the top level directory?

**Comment by dmitshur** [comment]
I think `font/sfnt` is good. That way the package name is `sfnt`. It’s pretty consistent with https://godoc.org/golang.org/x/image/font/sfnt and https://godoc.org/golang.org/x/image/font#pkg-subdirectories too.

**Comment by ConradIrwin** [comment]
Sounds good! Pull requests welcome :)

Sent via Superhuman ( https://sprh.mn/?vip=conradirwin@gmail.com )
