### ISSUE TITLE
Add continuous integration (CI).

### ISSUE THREAD

**Issue by dmitshur** [ConradIrwin/font#16]
Let's add CI to this repository. That way, it's easier to see whether the latest `master` is passing all tests and building successfully, as well as for PRs. This is especially important now that there are out-of-tree dependencies (that aren't vendored).

There are many valid choices of CI systems for open source Go packages. I will recommend we go with Travis CI. It's the one I've used for the last 4~ years and had a good experience with. I also have a good `.travis.yml` template that I can share. /cc @ConradIrwin @bramp

If you're okay with Travis CI, I can send a PR that adds a `.travis.yml` and adds a badge to README. @ConradIrwin, you'd need to enable this repo on https://travis-ci.org/ (since you're the owner).

**Comment by ConradIrwin** [comment]
activated on travis! go wild — do you have permission to access travis or do I have to do more?

Sent via Superhuman ( https://sprh.mn/?vip=conradirwin@gmail.com )

**Comment by dmitshur** [comment]
Thanks. It looks like I do. I'll let you know there's anything else.

**Comment by ConradIrwin** [comment]
Also, do you want to add dep to manage the dependencies? 👀 

Sent via Superhuman ( https://sprh.mn/?vip=conradirwin@gmail.com )

**Comment by dmitshur** [comment]
I don't have strong opinions on dependency management in this repo. I'll defer that decision to you.

I'm okay with things as they are (i.e., always fetching latest with `go get -u`), as well as `dep`. You might also want to consider the [new `vgo` experiment](https://research.swtch.com/vgo).
