### ISSUE TITLE
Misalignment with parsing of Lookup Records

### ISSUE THREAD

**Issue by npillmayer** [ConradIrwin/font#19]
When parsing testdata/Roboto-BoldItalic.ttf, parsing of GSUB->Lookups gets misaligned.
Output of testing the current code:

--- FAIL: TestGSubLookupRecords (0.00s)
    parse_test.go:34: [0] lookup record of type GSUB_Single
    parse_test.go:34: [1] lookup record of type GSUB_Single
    parse_test.go:34: [2] lookup record of type GSUB_ChainingContext
    parse_test.go:34: [3] lookup record of type GSUB_Single
    parse_test.go:34: [4] lookup record of type GSUB_Single
    parse_test.go:34: [5] lookup record of type GSUB_Ligature
    parse_test.go:34: [6] lookup record of type GSUB_Single
    parse_test.go:34: [7] lookup record of type GSUB_Single
    parse_test.go:34: [8] lookup record of type GSUB_Single
    parse_test.go:34: [9] lookup record of type GSUB_Single
    parse_test.go:34: [10] lookup record of type GSUB_ChainingContext
    parse_test.go:34: [11] lookup record of type 8960
    parse_test.go:34: [12] lookup record of type 2750
    parse_test.go:34: [17] lookup record of type 2305
   […]
    parse_test.go:34: [31] lookup record of type 2343
    parse_test.go:34: [32] lookup record of type 10505
    parse_test.go:34: [33] lookup record of type 2349
    parse_test.go:34: [34] lookup record of type 12041

It finds 35 lookup records, which is correct, but really only just by chance (I think in total it re-aligns with sub-tables somehow, but nevertheless is off). GSUB lookup types like 2315 aren't valid.  

The expected output should be:

    parse_test.go:34: [0] lookup record of type GSUB_Single
    parse_test.go:34: [1] lookup record of type GSUB_Single
    parse_test.go:34: [2] lookup record of type GSUB_Single
    parse_test.go:34: [3] lookup record of type GSUB_Ligature
    parse_test.go:34: [4] lookup record of type GSUB_ChainingContext
    parse_test.go:34: [5] lookup record of type GSUB_Single
    parse_test.go:34: [6] lookup record of type GSUB_Ligature
    parse_test.go:34: [7] lookup record of type GSUB_Ligature
    parse_test.go:34: [8] lookup record of type GSUB_ChainingContext
    parse_test.go:34: [9] lookup record of type GSUB_Single
    parse_test.go:34: [10] lookup record of type GSUB_Single
    parse_test.go:34: [11] lookup record of type GSUB_Single
    parse_test.go:34: [12] lookup record of type GSUB_Ligature
    parse_test.go:34: [13] lookup record of type GSUB_Single
    parse_test.go:34: [14] lookup record of type GSUB_Single
    parse_test.go:34: [15] lookup record of type GSUB_Single
    parse_test.go:34: [16] lookup record of type GSUB_Ligature
    parse_test.go:34: [17] lookup record of type GSUB_Ligature
    parse_test.go:34: [18] lookup record of type GSUB_Ligature
    parse_test.go:34: [19] lookup record of type GSUB_Single
    parse_test.go:34: [20] lookup record of type GSUB_Single
    parse_test.go:34: [21] lookup record of type GSUB_Single
    parse_test.go:34: [22] lookup record of type GSUB_Single
    parse_test.go:34: [23] lookup record of type GSUB_Single
    parse_test.go:34: [24] lookup record of type GSUB_Single
    parse_test.go:34: [25] lookup record of type GSUB_Single
    parse_test.go:34: [26] lookup record of type GSUB_Single
    parse_test.go:34: [27] lookup record of type GSUB_Single
    parse_test.go:34: [28] lookup record of type GSUB_Single
    parse_test.go:34: [29] lookup record of type GSUB_Single
    parse_test.go:34: [30] lookup record of type GSUB_Single
    parse_test.go:34: [31] lookup record of type GSUB_Single
    parse_test.go:34: [32] lookup record of type GSUB_ChainingContext
    parse_test.go:34: [33] lookup record of type GSUB_Single
    parse_test.go:34: [34] lookup record of type GSUB_Single

--------------------

I'll provide a fix, if this package is still maintained.

**Comment by npillmayer** [comment]
The Travis CI build obviously failes due to an illegal call to `go vet` in the pipeline (`go tool vet` instead of `go vet`).

**Comment by ConradIrwin** [comment]
This was fixed.

@npillmayer I've made you a collaborator on this repo, thank you for the high quality change! Feel free to push more fixes that you need (it's best if you use the PR mechanism, but if you don't hear back in a reasonable time, I trust your judgement).
